### ISSUE TITLE
Meme stops running in datamonkey

### ISSUE THREAD

**Issue by SIlviaHinojosa** [veg/datamonkey-js#170]
Hi 

I´ve been trying to use MEME for the past two weeks and sometimes it runs and sometimes it doesn´t but in the log file I do not get any error or warning saying why it stops.  Here is the lattest job I tried to run.
[log(1).txt](https://github.com/veg/hyphy/files/2527197/log.1.txt)

**Comment by rdvelazquez** [comment]
@SIlviaHinojosa My apologies for the delayed response. If you are still encountering this issue could you try the following:
- Run you analysis on staging.datamonkey.org to see if the issue persists in the newer version.
- Send me a copy of the input files or links to the analyses so that I can look into what is causing the issue.
