### ISSUE TITLE
GARD results description confusing (at least)

### ISSUE THREAD

**Issue by matsen** [veg/datamonkey-js#188]
Hello good Datamonkey folks--

I was running an example data set through GARD and got the following result

![image](https://user-images.githubusercontent.com/112708/58041266-84c6c380-7aec-11e9-8a48-14d4774bee5b.png)

perhaps you can see the full output at http://datamonkey.org/gard/5ce2da060a802902de314486 .

The highlighted text seems to me to contrast with the results table. Am I missing something?

I did use this file in teaching last year (which resulted in [this link that I saved but doesn't seem to give results](http://datamonkey.org/gard/5ad88315fbe9ab580f8f73cb)) and I thought that it showed significant changes of topology through the alignment. I could be remembering incorrectly though.

Thanks!

Erick

**Comment by rdvelazquez** [comment]
Hi @matsen,

Thanks for reaching out with your GARD issue. We always appreciate the feedback!

The link from the previous analysis can be accessed here: http://previousresults.datamonkey.org/gard/5ad88315fbe9ab580f8f73cb (If you have a previous results url that you can't view, you can add "previousresults" to the front of the url to view it. We updated the way results files are hosted and haven't gotten around to a more seamless approach yet). The two results however seem to be from different sequence alignments though (the new one has 36 sequences and 1707 sites; the old one has 13 sequences and 207 sites).

The highlighted text and Kishino Hasegawa results table do _seem_ to be in conflict however they are describing related but different things.
- The highlighted text: Is describing the results of testing the best break point model to look at how much of the improvement in c-AIC can be attributed to topological differences between partitions rather than branch lengths. We fit a model on the partitioned data letting the branch lengths vary between partitions but keep the tree topology constant. We then compare this c-AIC with the c-AIC for the best model (letting both branch lengths and topology vary)
- The Kishino Hasegawa table: is evaluating single break point models (a separate model for each break point) and looking at how much support is provided for that break point by the partition on the left and the partition on the right. 

@spond may be able to speak to this more, but from my understanding of what GARD is doing, the Kishino Hasegawa table is not very informative because _partitions_ and not _breakpoints_ are the unit of recombination... As your example results file nicely illustrates, there are instances where two individual _break points_ may not have strong support however the three _partitions_ which these two break points form _do_ have strong support.

Hopefully that was only somewhat confusing and also a bit helpful ; )

Please let us know if you have other questions.

Best,
Ryan

**Comment by matsen** [comment]
That's totally helpful on all fronts!

Feel free to close this issue, but some text describing the differences here could help folks like me.

Re previousresults, I did note that the original and partitioned data sets do not appear available from that link.

**Comment by rdvelazquez** [comment]
Sorry for the delayed response. The new version of GARD (with HyPhy 2.5) doesn't include the Kishino Hasegawa table.

As far as getting your old datasets...
 > Re previousresults, I did note that the original and partitioned data sets do not appear available from that link.

The original and partitioned data sets are available if you remove the "previousresults" from the URL (straight forward I know 🤷‍♂)

- Original file: http://datamonkey.org/gard/5ad88315fbe9ab580f8f73cb/original_file/original.fasta
- Partitioned Dataset: http://previousresults.datamonkey.org/gard/5ad88315fbe9ab580f8f73cb/screened_data/

**Comment by rdvelazquez** [comment]
Also, here's your data run through HyPhy 2.5 for reference: http://staging.datamonkey.org/gard/5d03b5451e9b8e1cd9a29d6b
