### ISSUE TITLE
Restore FASTA features

### ISSUE THREAD

**Issue by stephenshank** [veg/datamonkey-js#218]
FASTA features such as:

- the option to view MSAs
- the BUSTED tree/alignment widget

 are unavailable on datamonkey-js 1.5.2. This is perhaps related to changes in HyPhy vision's logic for handling the `fasta` prop, i.e. :

https://github.com/veg/hyphy-vision/commit/e647c7db240ff148dc01a8e48e3479c79dd82acf#diff-9c152f8eefaf7dc40462a0e9f8d3b9f1

but I've yet to definitively confirm this.

**Comment by stevenweaver** [comment]
Hi Stephen, 

If I recall correctly, I made this change because including the msa in the results does not follow hyphy results schema, and requires data munging in order to get the view to work outside of datamonkey, which is undesirable. 

If you work with hyphy-vision directly, I can make the necessary changes to datamonkey-js directly when it comes time for release.

Thanks for bringing this issue to attention.

Best,
Steven
