### ISSUE TITLE
Difficulty (inconsistency?) running GARD

### ISSUE THREAD

**Issue by matsen** [veg/datamonkey-js#286]
Hello there--

I'm trying to reproduce https://doi.org/10.1101/2020.03.30.015008 Figure 3 as a class exercise.

When I submit files I get no action, just a screen with a strange horizontal bar:

![Screenshot 2020-05-17 at 3 01 09 AM](https://user-images.githubusercontent.com/112708/82141552-78527500-97eb-11ea-87c8-564b9cdfd693.png)

It did work once, but unfortunately (oops!) with unaligned sequences, resulting in http://datamonkey.org/gard/5ec1081f299cb9159cf1d237 . When I try resubmitting with the same file, it doesn't work.

Thank you!

**Comment by spond** [comment]
Dear @matsen,

Sorry for this buggy behavior. Could you share the alignment that you were uploading? I want to make sure I can reproduce the issue.

Best,
Sergei

**Comment by stevenweaver** [comment]
Dear @matsen, 

After looking through our nginx logs, this is due to an embarrassing bug that will be resolved ASAP. 

If you navigate to http://datamonkey.org/gard/ and try using the form, it will result in the error that you are seeing. If you navigate to http://datamonkey.org/gard without a trailing `/`, it will work. 

I will follow-up here after a fix is implemented. 

Best,
Steven

**Comment by matsen** [comment]
Amazing! It's running now.

**Comment by stevenweaver** [comment]
Dear @matsen, 

Great! I also pushed a fix this morning to resolve any inconsistencies so that students will not inadvertently run into the same issue. 

Best,
Steven
