### ISSUE TITLE
Why there are some high values in MEME with the plot Beta+ vs Sites?

### ISSUE THREAD

**Issue by MauriAndresMU1313** [veg/datamonkey-js#493]
Hi! 
I read some articles to interpret the result of MEME; however, I couldn't find out if this is an issue or not.
Well in the plot a little amount of beta+ values are too high, for example, one has a value of 10.000!
Here is a figure of my plot: 
![Screenshot_1](https://user-images.githubusercontent.com/68199472/123881993-d7058000-d913-11eb-910d-6065b1e13018.png)
This is an issue? 
I must delete that value? 
I think that maybe is an issue because when a value is too high is a value to ignore. 
Anyway, I just looking for some help or recommendation. 
Thank!

**Comment by spond** [comment]
Dear @MauriAndresMU1313,

This is fairly normal behavior; you effectively have infinite &omega; rates for some sites. This can occur if you have "saturated" sites, or sites where only non-synonymous substitution occur. Remember that you should **never** use a point estimate from MEME to assess significance -- always use the p-value reported by the test.

Best,
Sergei

**Comment by MauriAndresMU1313** [comment]
Great to know that! Thank you for your comment! Only in the case that you know some article or protocol to interpret MEME´s result, could you share the name and author here? I read some articles; however, maybe you know the one that I don´t read yet!
Anyway, thank you!
Best!

**Comment by MauriAndresMU1313** [comment]
Hi again, sorry for the insistence. I need to know what to do because I´m plotting my data and I think that for your comment I must take into cont the p-values of my data? I mean plot the p-values, not the dN-dS vs sites? That is correct? Again sorry for the insistence; however, I can´t find out of some article or page to how to interpreting the result of MEME to plot.  Here an example of one of my analyses: [https://datamonkey.org/meme/60be6abdaeae26084a6f83a3](url)
Thank!

**Comment by spond** [comment]
Dear @MauriAndresMU1313,

You can definitely plot dN-dS (or &beta;+/&alpha; for MEME). I would suggest you "gate" high values, so for example if this value is >50 you can treat it as infinite.

What I mean by using p-values is that if you wish to say "site X is under selection", you should always consult the p-value for this site, not use &beta;+ values for this determination.

Best,
Sergei

**Comment by MauriAndresMU1313** [comment]
Hi again, I need your help again, well it´s more about your opinion. I plotted some of my analysis in data monkey with 3 different methods: SLAC, FEL, and MEME. Here the plot: 
![x](https://user-images.githubusercontent.com/68199472/125092782-b077df80-e09f-11eb-86af-3b463f3d3321.png)

In MEME I plotted the positive selection (beta+), well my question is: 
What do you think? 
Well in my case I think that there is something weird, I mean there are a lot of values close to 1. This is weird in the sense of natural selection. This a surface protein of some pathogens (viruses) so natural selection act in a strong way in some sites; however, I keep thinking that is weird to have so many sites with values close or equal to 1. 
Do you think that my concern is correct? 
Any comment is welcome!
Thank! @spond

**Comment by MauriAndresMU1313** [comment]
I forgot: the y-axis are: (1): dN-dS, (2): omega and (3): beta+

**Comment by spond** [comment]
Dear @MauriAndresMU1313,

This is not surprising, but is quite counter-intuitive. First, I would plot &beta;<sub>+</sub> / &alpha; because it is comparable to dN/dS from FEL. You'll have to deal with cases &alpha; = 0 by setting the ratio to some large number. Here's why you may find a large number of &beta;<sub>+</sub> = 1.

Imagine you have a site which is subject only to negative selection, or is evolving neutrally. The MEME model assumes that the evolution at this site is described by 


1. Fraction p- at rate &beta;- < &alpha;
2. Fraction 1-p- at rate &beta;+ ≥ &alpha;

If there is no evidence of positive selection at a site, then MEME can do one of two things

1. Move &beta;+ to the neutral regime (i.e. &beta;+ = &alpha; or dN/dS = 1)
2. Set p- = 1, i.e. place 0 weight in the &beta;+ class, which means that &beta;+ cannot be estimated (it will be set to arbitrary value).

I think the sensible way to plot the selected component of the MEME model would be as follows

1.  If p- = 1, do not plot anything (&beta;+ is not estimable).
2. If p- < 1, then plot &beta;+ / &alpha;
3. Mark sites that have p < 0.05 on all plots. 

Best,
Sergei

**Comment by MauriAndresMU1313** [comment]
Thanks for your continue support, I going to follow your advice!
